### ISSUE TITLE
which lisence?

### ISSUE THREAD

**Issue by naveedbsh** [Anish-U/NewsGrid#4]

**Comment by abdullahzubair109** [comment]
@Anish-U  I hope this message finds you well.

We recently integrated your project into our medical report system and found it to be an excellent fit for our needs. However, we noticed that the repository currently lacks a specified license.

To ensure we are compliant with legal and ethical standards, we kindly request that you add a license to the repository. Additionally, we seek your permission to reuse and modify the codebase as required for our project.

**Comment by anish-u** [comment]
Thank you @abdullahzubair109  for your positive feedback on the project and for integrating it into your medical report system. I’m glad to hear that it meets your needs. 

Regarding the license, I appreciate you bringing this to my attention. I will promptly add a license to the repository. Additionally, I am happy to grant permission for anyone to reuse and modify the codebase as required for their project.
